from django.core.management.base import BaseCommand
from source.models import *

class Command(BaseCommand):
    args = '<foo bar ...>'
    help = 'our help string comes here'

    def handle(self, *args, **options):
        actor1 = Actor(name="Hugh Jackman")
        actor1.save()
        actor2 = Actor(name="Zac Effron")
        actor2.save()
        actor3 = Actor(name="Zendaya Coleman")
        actor3.save()
        actor4 = Actor(name="Chadwick Boseman")
        actor4.save()
        actor5 = Actor(name="Michael B. Jordan")
        actor5.save()
        actor6 = Actor(name="Lupito Nyong'o")
        actor6.save()
        actor7 = Actor(name="Anthony Gonazalez")
        actor7.save()
        actor8 = Actor(name="Gael García Bernal")
        actor8.save()
        actor9 = Actor(name="Benjamin Bratt")
        actor9.save()
        actor10 = Actor(name="Tom Hiddleston")
        actor10.save()
        actor11 = Actor(name="Eddie Redmayne")
        actor11.save()
        actor12 = Actor(name="Maisie Williams")
        actor12.save()
        actor13 = Actor(name="")
        actor13.save()
        actor14 = Actor(name="")
        actor14.save()

        movie1 = Movie(title="The Greates Showman", blurb="Celebrates the birth of show business, and tells of a visionary who rose from nothing to create a spectacle that became a worldwide sensation.", cover="img/MovieCovers/TheGreatestShowman.jpg", rating= 8.0 ,duration="139", director="Michael Gracey", certificate="0", releaseDate="2017-12-26")
        movie1.save()
        movie1.cast.add(actor1)
        movie1.cast.add(actor2)
        movie1.cast.add(actor3)

        movie2 = Movie(title="Black Panther", blurb="T'Challa, after the death of his father, the King of Wakanda, returns home to the isolated, technologically advanced African nation to succeed to the throne and take his rightful place as king.", cover="img/MovieCovers/BlackPanther.jpg", rating= 7.1 ,duration="134", director="Ryan Coogler", certificate="12A", releaseDate="2018-02-13")
        movie2.save()
        movie2.cast.add(actor4)
        movie2.cast.add(actor5)
        movie2.cast.add(actor6)

        movie3 = Movie(title="Coco", blurb="Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.", cover="img/MovieCovers/Coco.jpg", rating=8.6  ,duration="105", director="Lee Unkrich, Adrian Molina", certificate="0", releaseDate="2018-01-19")
        movie3.save()
        movie3.cast.add(actor7)
        movie3.cast.add(actor8)
        movie3.cast.add(actor9)

        movie4 = Movie(title="Early Man", blurb="Set at the dawn of time, when prehistoric creatures and woolly mammoths roamed the earth, Early Man tells the story of Dug, along with sidekick Hognob as they unite his tribe against a mighty enemy Lord Nooth and his Bronze Age City to save their home.", cover="img/MovieCovers/EarlyMan.jpg", rating=6.4  ,duration="99", director="Nick Park", certificate="0", releaseDate="2018-01-26")
        movie4.save()
        movie4.cast.add(actor10)
        movie4.cast.add(actor11)
        movie4.cast.add(actor12)

        movie5 = Movie(title="", blurb="", cover="img/MovieCovers/.jpg", rating=  ,duration="", director="", certificate="", releaseDate="201--")
        movie5.save()
        movie5.cast.add(actor)
        movie5.cast.add(actor)
        movie5.cast.add(actor)

        movie6 = Movie(title="", blurb="", cover="img/MovieCovers/.jpg", rating=  ,duration="", director="", certificate="", releaseDate="201--")
        movie6.save()
        movie6.cast.add(actor)
        movie6.cast.add(actor)
        movie6.cast.add(actor)

        movie7 = Movie(title="", blurb="", cover="img/MovieCovers/.jpg", rating=  ,duration="", director="", certificate="", releaseDate="201--")
        movie7.save()
        movie7.cast.add(actor)
        movie7.cast.add(actor)
        movie7.cast.add(actor)

        movie8 = Movie(title="", blurb="", cover="img/MovieCovers/.jpg", rating=  ,duration="", director="", certificate="", releaseDate="201--")
        movie8.save()
        movie8.cast.add(actor)
        movie8.cast.add(actor)
        movie8.cast.add(actor)

        movie9 = Movie(title="", blurb="", cover="img/MovieCovers/.jpg", rating=  ,duration="", director="", certificate="", releaseDate="201--")
        movie9.save()
        movie9.cast.add(actor)
        movie9.cast.add(actor)
        movie9.cast.add(actor)

        movie10 = Movie(title="", blurb="", cover="img/MovieCovers/.jpg", rating=  ,duration="", director="", certificate="", releaseDate="201--")
        movie10.save()
        movie10.cast.add(actor)
        movie10.cast.add(actor)
        movie10.cast.add(actor)

        screen1 = Screen(standardSeats=50 ,vipSeats=20 )
        screen1.save()
        screen2 = Screen(standardSeats=50 ,vipSeats=20 )
        screen2.save()
        screen3 = Screen(standardSeats=50 ,vipSeats=20 )
        screen3.save()
        screen4 = Screen(standardSeats=70 ,vipSeats=30 )
        screen4.save()
        screen5 = Screen(standardSeats=70 ,vipSeats=30 )
        screen5.save()

        s1m1 = Screening(movie_id = movie1 , screen_id = screen1, reservedSeats = 0)
        s1m1.save()
        s2m1 = Screening(movie_id = movie1 , screen_id = screen1, reservedSeats = 10)
        s2m1.save()
        s3m1 = Screening(movie_id = movie1 , screen_id = screen2, reservedSeats = 3)
        s3m1.save()

        s1m2 = Screening(movie_id = movie2 , screen_id = screen2, reservedSeats = 0)
        s1m2.save()
        s2m2 = Screening(movie_id = movie2 , screen_id = screen2, reservedSeats = 10)
        s2m2.save()

        s1m3 = Screening(movie_id = movie3 , screen_id = screen3, reservedSeats = 0)
        s1m3.save()
        s2m3 = Screening(movie_id = movie3 , screen_id = screen3, reservedSeats = 40)
        s2m3.save()
        s3m3 = Screening(movie_id = movie3 , screen_id = screen3, reservedSeats = 23)
        s3m3.save()

        s1m4 = Screening(movie_id = movie4 , screen_id = screen4, reservedSeats = 0)
        s1m4.save()
        s2m4 = Screening(movie_id = movie4 , screen_id = screen4, reservedSeats = 16)
        s2m4.save()

        s1m5 = Screening(movie_id = movie5 , screen_id = screen5, reservedSeats = 0)
        s1m5.save()

        t1m1 = Timing(screening_id = s1m1, date = '2018-02-15' , time = '11:20:00' )
        t1m1.save()
        t2m1 = Timing(screening_id = s2m1, date = '2018-02-15' , time = '16:20:00' )
        t2m1.save()
        t3m1 = Timing(screening_id = s3m1, date = '2018-02-16', time = '19:20:00')
        t3m1.save()

        t1m2 = Timing(screening_id = s1m2, date = '2018-02-15', time = '15:55:00')
        t1m2.save()
        t2m2 = Timing(screening_id = s2m2, date = '2018-02-16', time = '12:50:00')
        t2m2.save()

        t1m3 = Timing(screening_id = s1m3, date = '2018-02-15', time = '11:00:00')
        t1m3.save()
        t2m3 = Timing(screening_id = s2m3, date = '2018-02-15', time = '18:10:00')
        t2m3.save()
        t3m3 = Timing(screening_id = s3m3, date = '2018-02-15', time = '17:25:00')
        t3m3.save()

        t1m4 = Timing(screening_id = s1m4, date = '2018-02-16', time = '14:15:00')
        t1m4.save()
        t2m4 = Timing(screening_id = s2m4, date = '2018-02-16', time = '20:00:00')
        t2m4.save()

        t1m5 = Timing(screening_id = s1m5, date = '2018-02-15', time = '15:40:00')
        t1m5.save()
